### ISSUE TITLE
[Compatibility Issue] - Broken Custom CSS

### ISSUE THREAD

**Issue by BigFlubba** [SmolAlli/Themes#7]
I am using this custom CSS snippet and with minimal mode enabled it breaks the bottom of it. Can this be fixed somehow?

```css
/* outline to folders */
.expandedFolderBackground-1kSAf6 {
  background-color: rgb(0, 0, 0);
  box-shadow: 0px 0px 8px 2px rgb(0, 80, 255);
  border-radius: 20px 20px 30px 30px;
}
/* get rid of border when folder is collapsed */
.expandedFolderBackground-1kSAf6.collapsed-uGXEbi {
  box-shadow: none;
  border: none;
}
```

Minimal Mode Disabled:
![image](https://user-images.githubusercontent.com/69104450/177063553-49bc547d-1933-4b16-84ff-0acb725d9f31.png)

Minimal Mode Enabled:
![image](https://user-images.githubusercontent.com/69104450/177063609-09de1b15-7ad4-4fb1-94ee-0ad0911e4bdb.png)

What it does is cut off the very bottom of the folder and overlaps it with the guild icon. Here is a more clear example.

Disabled:
![image](https://user-images.githubusercontent.com/69104450/177063730-229ba657-ca57-4df2-adb5-aff9c54f2a76.png)

Enabled:
![image](https://user-images.githubusercontent.com/69104450/177063701-796c446d-91e4-4cad-a7dc-4d0b9b9c5e92.png)
